LANG_MAP = {
    "繁體中文": {
        "開始錄製": "開始錄製",
        "暫停/繼續": "暫停/繼續",
        "停止": "停止",
        "回放": "回放",
        "MiniMode": "MiniMode",
        "Script路徑": "Script路徑",
        "快捷鍵": "快捷鍵",
        "關於": "關於",
        "重複次數:": "重複次數:",
        "次": "次",
        "重複時間": "重複時間",
        "Script:": "Script:",
        "重新命名": "重新命名",
        "Script": "Script",
        "合併並儲存": "合併並儲存",
        "所有Script": "所有Script",
        "新Script名稱：": "新Script名稱：",
        "確定": "確定",
        "所有Script": "所有Script",
        "清空": "清空",
        "加入": "加入",
        "移除": "移除",
        "延遲秒數:": "遲延秒數:",
        "Language": "Language",
        "回放速度:": "回放速度:",
        "總運作": "總運作",
        "單次": "單次",
        "錄製": "錄製",
        "刪除": "刪除",
        "儲存": "儲存",
        "重複間隔": "重複間隔",
        "剩餘": "剩餘"
    },
    "日本語": {
        "開始錄製": "録画開始",
        "暫停/繼續": "一時停止 / 再開",
        "停止": "停止",
        "回放": "再生",
        "MiniMode": "ミニモード",
        "Script路徑": "Scriptのパス",
        "快捷鍵": "ホットキー",
        "關於": "アバウト",
        "重複次數:": "繰り返し回数：",
        "次": "回",
        "重複時間": "間隔時間",
        "Script:": "Script：",
        "重新命名": "名前を変更",
        "Script": "Script",
        "合併並儲存": "結合して保存",
        "所有Script": "全Script",
        "新Script名稱：": "新しい名前：",
        "確定": "OK",
        "延遲秒數:": "ディレイ（秒）：",
        "Language": "言語",
        "回放速度:": "再生速度：",
        "總運作": "総再生",
        "單次": "1回のみ",
        "錄製": "録画",
        "刪除": "削除",
        "儲存": "保存",
        "重複間隔": "繰り返し間隔",
        "剩餘": "残り"
    },
    "English": {
        "開始錄製": "Start Recording",
        "暫停/繼續": "Pause/Resume",
        "停止": "Stop",
        "回放": "Play",
        "MiniMode": "Mini Mode",
        "Script路徑": "Script Path",
        "快捷鍵": "Hotkey",
        "關於": "About",
        "重複次數:": "Repeat:",
        "次": "times",
        "重複時間": "Interval",
        "Script:": "Script:",
        "重新命名": "Rename",
        "Script": "Script",
        "所有Script": "All Scripts",
        "新Script名稱：": "New Script Name:",
        "確定": "Confirm",
        "延遲秒數:": "Delay (sec):",
        "Language": "Language",
        "回放速度:": "Playback Speed:",
        "總運作": "Total Runs",
        "單次": "Single Run",
        "錄製": "Record",
        "刪除": "Delete",
        "儲存": "Save",
        "重複間隔": "Repeat Interval",
        "剩餘": "Remain"
    }
}